query TRANSLATE ($input: TranslateInput!) {
    translate(input: $input)
}
query IMAGE ($input: ImageInput!) {
    image(input: $input)
}
query EXAMPLE ($input: TranslateInput!) {
    example(input: $input)
}
