
query translate($input: TranslateInput!) {
    translate(input: $input)
}

query image($input: ImageInput!) {
    image(input: $input)
}

query example($input: TranslateInput!) {
    example(input: $input)
}
