fragment UserDetails on User {
	username
	email
    image
	__typename
}

mutation login($data: LoginInput) {
	login(data: $data) {
		access_token
		expires_in
		user {
			...UserDetails
		}
	}
}

mutation refresh_token($refresh: Boolean) {
	refresh_token(refresh: $refresh) {
		access_token
		expires_in
	}
}

mutation logout {
	logout {
		status
		message
	}
}

mutation register($data: RegisterInput) {
	register(data: $data) {
		access_token
		expires_in
		user {
			...UserDetails
		}
	}
}

query me {
	me {
		...UserDetails
	}
}
