fragment UserDetails on User {
	username
	email
    image
	__typename
}

mutation LOGIN ($data: LoginInput) {
	login(data: $data) {
        ...UserDetails
	}
}

mutation LOGOUT {
	logout {
		status
		message
	}
}

mutation REGISTER ($data: RegisterInput) {
	register(data: $data) {
        ...UserDetails
	}
}

query USER {
	user {
		...UserDetails
	}
}
