mutation login($data: LoginInput) {
  login(data: $data) {
      access_token
      expires_in
      user {
          username
          email
      }
  }
}

mutation refresh_token($refresh: Boolean) {
  refresh_token(refresh: $refresh) {
      access_token
      expires_in
  }
}

mutation logout {
logout {
    status
    message
  }
}

mutation register($data: RegisterInput) {
  register(data: $data) {
      access_token
      expires_in
      user {
          username
          email
      }
  }
}

query me {
    me {
        username
        email
    }
}
