query decks($amount: Int, $page: Int!, $query: String, $filter: FilterClause!) {
  decks (first: $amount, page: $page, search: $query ,filter: [$filter]) {
    paginatorInfo {
      total
      lastPage
      hasMorePages
    }
    data {
      id
      title
      image
      created_at
      cards_count
      visibility
      lang_source {
          locale
          name
      }
      lang_target {
          locale
          name
      }
      slug
      user {
        username
      }
    }
  }
}
