query DECK_EDITOR {
    languages {
        id
        locale
        name
    }
    __type(name: "Visibility") {
        enumValues {
            name
            description
        }
    }
}

query DECK_TO_EDIT ($slug: String!) {
    deck (slug: $slug) {
        id
        title
        description
        image
        lang_source {
            id
        }
        lang_target {
            id
        }
        visibility
        slug
        cards {
            id
            question
            answer
            example_question
            example_answer
            image
        }
    }
}

mutation CREATE_DECK ($input: CreateDeckInput!) {
  createDeck(input: $input) {
    id
    slug
    cards {
        id
    }
  }
}

mutation UPDATE_DECK ($input: UpdateDeckInput!) {
  updateDeck(input: $input) {
    id
    slug
    cards {
        id
    }
  }
}

mutation REMOVE_DECK ($id: ID!) {
  removeDeck(id: $id) {
      id
  }
}

mutation CREATE_CARD ($input: CreateCardInput!) {
  createCard(input: $input) {
    id
  }
}

mutation UPDATE_CARD ($input: UpdateCardInput!) {
  updateCard(input: $input) {
    id
  }
}

mutation REMOVE_CARD ($id: ID!) {
  removeCard(id: $id) {
      id
  }
}
