query deckEditor {
    languages {
      id
      locale
      name
    }
    __type(name: "Visibility") {
        enumValues {
            name
            description
        }
    }
}

mutation createDeck($input: CreateDeckInput!) {
  createDeck(input: $input) {
    id
    slug
  }
}

mutation upload($file: Upload!) {
    upload(file: $file)
}
