query profile($username: String!, $isAuthenticated: Boolean!) {
  profile(username: $username) {
    ... on AuthUser {
    id @include(if: $isAuthenticated)
    username
    email
    editable
    cards_count
      decks {
        title
        description
        cards_count
        image
        slug
        created_at
        visibility
      }
    }
    ... on User {
    username
    email
    cards_count
      decks {
        title
        description
        cards_count
        image
        slug
        created_at
        visibility
      }
    }
  }
}
mutation editProfile($id: Int!, $username: String, $email: String, $password: String, $password_confirmation: String) {
  editProfile(
      id: $id, username: $username, email: $email, password: $password, password_confirmation: $password_confirmation
  ) {
      username
      email
  }
}

mutation removeProfile($id: Int!) {
  removeProfile(
      id: $id
  ) {
      username
      email
  }
}
