query PROFILE ($username: String!) {
  profile(username: $username) {
    ... on AuthUser {
    id
    username
    email
    image
    editable
    cards_count
      decks {
        id
        title
        description
        cards_count
        image
        slug
        created_at
        visibility
      }
    }
    ... on User {
    username
    email
    image
    cards_count
      decks {
        title
        description
        cards_count
        image
        slug
        created_at
        visibility
      }
    }
  }
}
mutation EDIT_PROFILE ($data: EditProfileInput) {
  editProfile(data : $data) {
      username
      email
      image
  }
}

mutation CHANGE_AVATAR ($data: ChangeAvatarInput) {
  changeAvatar(data : $data) {
      username
      email
      image
  }
}

mutation REMOVE_PROFILE ($id: Int!) {
  removeProfile(id: $id) {
      username
      email
  }
}
